[package]
name = "testlib"
version = "0.1.0"
edition = "2018"

[dependencies]
foo = { path = "../foo" }
bar = { path = "../bar" }
solana-program = "1.7.8"
solana-program-test = "1.7.8"
solana-sdk = "1.7.8"